### ISSUE TITLE
Pouzivat dlhe kody na Prifuku

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#106]
Feature #106 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/106
Author: <strong>Martin Sucha</strong>
Assignee: Jakub Marek
Priority: Urgent
Start date: 04/27/2012

<div class="wiki"> <p>Chceme updatnut Identification tak, aby na FaF sa pouzivali dlhe kody.<br/>Eventuelne chceme pouzivat dlhe kody aj na PriF.</p> </div>

<hr>

<em>Created by <strong>Martin Sucha</strong> on 2012-04-27 at 14:14:43+02:00</em>

<ul><li><strong>Start date</strong> set to <i>04/27/2012</i></li><li><strong>Priority</strong> set to <i>Normal</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Assignee</strong> set to <i>Jakub Marek</i></li><li><strong>Subject</strong> set to <i>Pouzivat dlhe kody na FaF</i></li><li><strong>Tracker</strong> set to <i>Feature</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>Chceme updatnut Identification tak, aby na FaF sa pouzivali dlhe kody. Eventu...</i> </li></ul>

**Comment by mrshu** [comment]
@tvinar @Sameth toto treba asi pozriet, nech to mozeme alebo zavriet alebo znova zacat riesit, v kontexte #223

**Comment by vidriduch** [comment]
@tvinar @Sameth @mrshu je tato issue este relevatna? #223 uz je uzavrena a vyzera ze PriF UK pouziva dlhe kody. Moze sa tato issue zavriet?

**Comment by mrshu** [comment]
Ja si myslim, ze sa moze zavriet. Velmi by vsak pomohlo, keby to @tvinar alebo @Sameth potvrdili.

**Comment by tvinar** [comment]
Ostal tam jeden bug, "nove" kratke kody sa nespravne triedia vo vysledkoch.
(Vsetky sa mapuju na XXX, co pravdepodobne znamena "nematchujem prislusny
regexp".) Otazka je, ci je to nove issue alebo dokoncenie tohto ;)
(Pravdepodobne vyzaduje zasah rozsahu cca 1 riadku)

--------------------------------------------------------------------------
Tomas Vinar, Associate Professor
Associate Dean for Information Technologies
Department of Applied Informatics
Faculty of Mathematics, Physics, and Informatics
Comenius University, Bratislava
E-mail: tomas.vinar@fmph.uniba.sk
Office: M163
Work Phone: +421-2-60295207

**Comment by mrshu** [comment]
@tvinar Z mojej strany ide o dokoncenie tohoto =)
