### ISSUE TITLE
Command na manipulaciu so season

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#135]
Feature #135 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/135
Author: <strong>Ivan Trančík</strong>
Priority: Low
Start date: 12/10/2012

<hr>

<em>Created by <strong>Ivan Trančík</strong> on 2012-12-10 at 14:23:42+01:00</em>

<ul><li><strong>Start date</strong> set to <i>12/10/2012</i></li><li><strong>Priority</strong> set to <i>Low</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Subject</strong> set to <i>Command na manipulaciu so season</i></li><li><strong>Tracker</strong> set to <i>Feature</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to  </li></ul>

**Comment by mrshu** [comment]
Na toto uz je celkom solidny tooling, aj ked nie uplne pomocou Symfony.
