### ISSUE TITLE
Novy system pravomoci a pristupovych prav

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#155]
Bug #155 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/155
Author: <strong>Dušan Plavák</strong>
Priority: Immediate
Target version: Velafakultne vysledky 2014/2015
Start date: 03/20/2013

<div class="wiki"> <p>Umoznit, aby sa vysledky zobrazovali len tym, co su prihlaseni a patria ku fakulte (su studentami fakulty, alebo zamestnancami fakulty, alebo sa o nich v tej ankete hovori to jest patria medzi v ankete hodnotenych teacherov, alebo su admini).</p> <p>Pritom mozno bude treba premysliet ten "system pravomoci" (tie booleany v Seasone).</p> </div>

<hr>

<em>Created by <strong>Dušan Plavák</strong> on 2013-03-20 at 13:19:51+01:00</em>

<ul><li><strong>Start date</strong> set to <i>03/20/2013</i></li><li><strong>Priority</strong> set to <i>Normal</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Subject</strong> set to <i>Novy access level - &quot;prihlaseni co patria k danej fakulte&quot;</i></li><li><strong>Tracker</strong> set to <i>Bug</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>Umoznit, aby sa vysledky zobrazovali len tym, co su prihlaseni a patria ku fa...</i> </li></ul>

**Comment by TomiBelan** [comment]
Hopla, toto uz je davno fixnute v 42aef57956ff29311e71fc245f712bb97e901bcc.
