### ISSUE TITLE
Vyriesit escapovanie trans tagov

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#169]
Task #169 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/169
Author: <strong>Tomáš Belan</strong>
Priority: Normal
Start date: 07/08/2013

<div class="wiki"> <p>Open-ended issue:</p> <p>V tomto konkretnom momente nemame (afaict) ziadnu dieru tohoto typu, ale treba najst nejaky sposob ako mat aj prekladany text aj escapovanie by default, v com sa neda lahko pomylit. Ci uz nejako ohackovat trans tagy, nech vedia escapovat, alebo si vyrobit vlastne, alebo prekladat nejako inak, alebo nieco este ine.</p> <p><a class="external" href="http://symfony.com/doc/current/book/translation.html">http://symfony.com/doc/current/book/translation.html</a><br/>"text translated between tags is never escaped"</p> </div>

<hr>

<em>Created by <strong>Tomáš Belan</strong> on 2013-07-08 at 23:21:29+02:00</em>

<ul><li><strong>Start date</strong> set to <i>07/08/2013</i></li><li><strong>Priority</strong> set to <i>Normal</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Subject</strong> set to <i>Vyriesit escapovanie trans tagov</i></li><li><strong>Tracker</strong> set to <i>Task</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>Open-ended issue:  V tomto konkretnom momente nemame (afaict) ziadnu dieru to...</i> </li></ul>

**Comment by TomiBelan** [comment]
Hopla, toto uz je davno fixnute v dbe62c757fb5d03e44d5843b7b51dd4e82eccb7d.
