### ISSUE TITLE
Zistovat ci som student podla pritomnosti zapisneho listu

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#189]
Feature #189 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/189
Author: <strong>Tomáš Belan</strong>
Assignee: Kamila Součková
Priority: Urgent
Target version: Velafakultne hlasovanie 2014/2015
Start date: 03/09/2015

<div class="wiki"> <p>Ked zistujeme z LDAPu, ludia co spravia statnice uz nemozu hlasovat. Mali by sme zistovat, ci dany clovek ma spravny zapisny list (sedi fakulta, ak.rok a semester) a v tom pripade dovolit hlasovanie.</p> <p>Aj fakulty by sme mali zistovat zo zapisnych listov a nie ako organizacne jednotky z LDAPu. (Aspon pre studentov. Ucitelia mozno musia ist cez LDAP.)</p> <p>Toto je iny issue nez #176, ktory je o uplnych absolventoch (ktori by mali nejake ine otazky a nevideli by zoznam predmetov).</p> </div>

<hr>

<em>Created by <strong>Tomáš Belan</strong> on 2015-03-09 at 13:23:47+01:00</em>

<ul><li><strong>Start date</strong> set to <i>03/09/2015</i></li><li><strong>Priority</strong> set to <i>Urgent</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Target version</strong> set to <i>Velafakultne hlasovanie 2014/2015</i></li><li><strong>Subject</strong> set to <i>Zistovat ci som student podla pritomnosti zapisneho listu</i></li><li><strong>Tracker</strong> set to <i>Feature</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>Ked zistujeme z LDAPu, ludia co spravia statnice uz nemozu hlasovat. Mali by ...</i> </li></ul>

**Comment by TomiBelan** [comment]
Hopla, toto uz je davno fixnute v 8d8e56e9a161cb9ca71d52bf6568fc6da5e6fda7.
