### ISSUE TITLE
Brat predmety iba z tych zapisnych listov co maju spravnu fakultu

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#190]
Feature #190 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/190
Author: <strong>Tomáš Belan</strong>
Priority: Urgent
Target version: Velafakultne hlasovanie 2014/2015
Start date: 03/09/2015

<div class="wiki"> <p>Povedzme ze studujem na dvoch fakultach naraz, a mam zapisane nejake predmety na FMFI a nejake na FM. Tak v ankete FMFI by som mal vidiet len tie predmety, co mam na FMFI. (A to aj vtedy, ked povedzme v ramci FMFI studia mam zapisany nejaky PriF/1-... predmet, tak by som ho mal vidiet v ankete FMFI.)</p> </div>

<hr>

<em>Created by <strong>Tomáš Belan</strong> on 2015-03-09 at 13:27:33+01:00</em>

<ul><li><strong>Start date</strong> set to <i>03/09/2015</i></li><li><strong>Priority</strong> set to <i>Urgent</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Target version</strong> set to <i>Velafakultne hlasovanie 2014/2015</i></li><li><strong>Subject</strong> set to <i>Brat predmety iba z tych zapisnych listov co maju spravnu fakultu</i></li><li><strong>Tracker</strong> set to <i>Feature</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>Povedzme ze studujem na dvoch fakultach naraz, a mam zapisane nejake predmety...</i> </li></ul>

**Comment by TomiBelan** [comment]
Hopla, toto uz je davno fixnute v 8d8e56e9a161cb9ca71d52bf6568fc6da5e6fda7.
