### ISSUE TITLE
Automatizovane importy cez votr

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#191]
Bug #191 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/191
Author: <strong>Tomáš Belan</strong>
Priority: Normal
Target version: Velafakultne hlasovanie 2014/2015
Start date: 03/09/2015

<div class="wiki"> <p>Postupy popisane na stranke <a class="external" href="https://svt-devel.fmph.uniba.sk/chiliproject/projects/anketa/wiki/Importy">https://svt-devel.fmph.uniba.sk/chiliproject/projects/anketa/wiki/Importy</a> by sme chceli automatizovat cez votr. Chceli by sme nejaky skript, ktory spustim, on si vypyta moje AIS meno a heslo, a bud vyprodukuje spravne CSV/XML/... subory, alebo to priamo importne do ankety.</p> <p>Matfyz je trochu specialny, lebo navyse importujeme z candlu. Takze importujuci mozno potrebuje aktualny rozvrh.xml. Ale okrem tohto jedneho suboru by nemal nic potrebovat, malo by mu stacit aby zadal nejake konkretne prikazy a hotovo.</p> <p>Poznamka: issue #86 navrhuje spravit v ankete webove UI na vkladanie importov do databazy, ale tento issue sa hlavne tyka tahania udajov z AISu. Myslim ze oboje staci cez konzolu, aspon zatial.</p> </div>

<hr>

<em>Created by <strong>Tomáš Belan</strong> on 2015-03-09 at 13:31:45+01:00</em>

<ul><li><strong>Start date</strong> set to <i>03/09/2015</i></li><li><strong>Priority</strong> set to <i>Normal</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Target version</strong> set to <i>Velafakultne hlasovanie 2014/2015</i></li><li><strong>Subject</strong> set to <i>Automatizovane importy cez votr</i></li><li><strong>Tracker</strong> set to <i>Bug</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>Postupy popisane na stranke https://svt-devel.fmph.uniba.sk/chiliproject/proj...</i> </li></ul>

**Comment by TomiBelan** [comment]
Toto som asi zabudol zavriet. `votr_export.py` bol pridany v 1074c29fa5e9c452c8d467e3562febb735b51566. Importy su (az na par "TODO" detailov) zdokumentovane na https://svt-devel.fmph.uniba.sk/w/anketa/importy/.
