### ISSUE TITLE
UI pre nevhodne komentare

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#192]
Feature #192 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/192
Author: <strong>Tomáš Belan</strong>
Assignee: Adam Dej
Priority: Normal
Target version: Velafakultne vysledky 2014/2015
Start date: 03/09/2015

<div class="wiki"> <p>Nevhodne komentare momentalne chodia cez email a oznacujeme ich cez raw SQL. Chceme to spravit user friendly, nech to ostatne fakulty zvladaju bez nasej pomoci.</p> <ul> <li>Chceme UI, kde postupne vidno <strong>vsetky</strong> komentare a clovek cez ne moze prejst (pred zobrazenim vysledkov).</li> <li>Chceme UI, kde vidno komentare co boli nahlasene ako nevhodne.</li> <li>Chceme UI pre dekana, kde je zoznam schovanych komentarov.</li> </ul> <p>Vsetci maju plno napadov, ako by to UI malo vyzerat a ako by sa malo ovladat. Urcite chceme, aby si to mohli rozdelit viaceri ludia, a aby nevyzadovalo klikanie mysou na kazdy "ok" komentar. Napriklad mne by sa pacilo mat navyse nieco klavesnicove, kde ked stlacim "A"/"N", tak sa to oznaci a prescrolluje sa na dalsi komentar. Niekto navrhoval nieco ako emailovy inbox. A tak dalej.</p> <p>V pripade komentarov, co niekto nahlasil ako nevhodne, by sa mi pacilo keby ludia mohli diskutovat ci je nevhodny alebo nie. (Aspon nam na matfyze by sa to hodilo;) Ale mozno to staci cez email, ako doteraz.</p> <p>Hlasenia si asi budeme musiet pamatat v databaze, podobne ako si pamatame nahlasenych chybajucich ucitelov. Mali by sme si pamatat, kto to nahlasil, aky dovod napisal, a ci sme to uz vybavili (ci uz pozitivne alebo negativne - to neukladame per-hlasenie ale pri samotnom komentari).</p> </div>

<hr>

<em>Created by <strong>Tomáš Belan</strong> on 2015-03-09 at 13:46:13+01:00</em>

<ul><li><strong>Start date</strong> set to <i>03/09/2015</i></li><li><strong>Priority</strong> set to <i>Normal</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Target version</strong> set to <i>Velafakultne hlasovanie 2014/2015</i></li><li><strong>Subject</strong> set to <i>UI pre nevhodne komentare</i></li><li><strong>Tracker</strong> set to <i>Feature</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>Nevhodne komentare momentalne chodia cez email a oznacujeme ich cez raw SQL. ...</i> </li></ul>

**Comment by tvinar** [comment]
Skontrolovat UI pre nevhodne komentare (asi je v poriadku)

**Comment by mrshu** [comment]
Seems good enough. Let's open up a new one if we find it inappropriate again.
