### ISSUE TITLE
Opt-in rezim

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#197]
Feature #197 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/197
Author: <strong>Tomáš Belan</strong>
Priority: Normal
Target version: Velafakultne vysledky 2014/2015
Start date: 03/09/2015

<div class="wiki"> <p>Keby to bolo fakt treba, chceme anketu vediet prepnut do "opt-in rezimu", v ktorom sa anketa ucitelov pri prvom prihlaseni opyta, ci suhlasia so zverejnenim ich vysledkov. Ak nebudu suhlasit, neuvidia ziadne vysledky, a nikto neuvidi ich vysledky. Myslim ze suhlas by asi mal byt vecny (nie ze to musia odklikavat kazdu sezonu).</p> <p>Predpokladam, ze aj opt-in rezim ako taky je globalne nastavenie. Lebo ak ho raz budeme potrebovat, asi budeme (aspon v danej instancii) musiet schovat aj vysledky starych rokov, co doteraz boli verejne.</p> </div>

<hr>

<em>Created by <strong>Tomáš Belan</strong> on 2015-03-09 at 14:23:36+01:00</em>

<ul><li><strong>Start date</strong> set to <i>03/09/2015</i></li><li><strong>Priority</strong> set to <i>Normal</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Target version</strong> set to <i>Velafakultne vysledky 2014/2015</i></li><li><strong>Subject</strong> set to <i>Opt-in rezim</i></li><li><strong>Tracker</strong> set to <i>Feature</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>Keby to bolo fakt treba, chceme anketu vediet prepnut do &quot;opt-in rezimu&...</i> </li></ul>

**Comment by tvinar** [comment]
deprecated lebo nevyhovuje sucasnym zakonom
