### ISSUE TITLE
Anketa po prihlásení vypíše prázdnu obrazovku

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/anketa#201]
Pravdepodobne problém s VOTRom - je potrebné updatnut na novú verziu (momentálne tam je verzia z júna?).

**Comment by TomiBelan** [comment]
Konkretna chyba sa asi da najst vo /var/log/httpd alebo podobne. Kedysi sme pri PHP chybach ukazovali kulturnu hlasku, kto vie co sa pokazilo. Samotny votr update vid #202.
