### ISSUE TITLE
Nefunguje export priradení učiteľ/študent z AIS2

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/anketa#204]
Spôsobené pravdepodobne zmenou interface (vyzerá pridanie nového podokna) v aplikácii RPZS003 - pravdepodobne ovplyvňuje aj ďalšie exporty z AISu. Exporty priradení učiteľov nateraz vyrobené ručne.

**Comment by TomiBelan** [comment]
Interface vyzera rovnako ako za mojich cias. Skor tipujem ze je proste stary votr. Zisiel by sa stack trace.

Vyrobene rucne = dufam ze proste rucne z AISu stiahnute CSV ktorym sa potom nakrmi `anketa:import:ucitel-predmet`, ze? Nie ze rucne menite databazu :)

**Comment by Sameth** [comment]
Hotovo, v Aise si pomenili nazvy (popridavali X na rozne miesta)
