### ISSUE TITLE
Default blokovania výsledkov konkrétneho učiteľa

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/anketa#205]
Urobiť nové globálne nastavenie, ktoré nastavuje príznak hideAllResults=0 alebo hideAllResults=1 pri vytvorení nového učiteľa (inými slovami: anketa je buď v permisívnom móde, keď default pre učiteľa je, že jeho výsledky sú viditeľné alebo v restriktívnom móde, keď default pre učiteľa je, že jeho výsledky nie sú viditeľné)

**Comment by Sameth** [comment]
Okej, snáď je to spravené (všade, muhahahahaha!). Ak sa nebudú obnovovať staršie dumpy, malo by sa to zachovať. Ak sa bude niekomu chcieť, môže checknúť, že som to nepofarmárčil.
