### ISSUE TITLE
Upraviť blokovanie výsledkov učiteľa

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/anketa#206]
Blokovanie výsledkov učiteľa v prípade, že má nastavené hideAllResults=1, práve pri všetkých otázkach, ktoré sú asociované s týmto učiteľom (t.j. obvykle sekcia predmet-učiteľ). Namiesto výsledkov sa zobrazí hláška "Tento učiteľ nesúhlasí so zverejnením jeho výsledkov." resp. "This teacher did not agree to publish the responses." 

(Toto už je pravdepodobne implementované, no ešte by tam mal byť ďalší kód, ktorý v niektorých prípadoch blokuje výsledky predmetu. Tento kód by nemal byť potrebný, otázky o predmete by nemali byť blokované. Kód asi zakomentovať, keby sa predsa len ukázalo, že ho treba ;))

Výnimka: používatelia s ADMIN privilégiami vidia všetky výsledky.
Možno výnimka (?): používatelia, ktorí majú privilégiá na report príslušnej katedry tiež vidia výsledky učiteľa priradeného k danej katedre.

**Comment by TomiBelan** [comment]
Doplnim momentalny status: Hlaska uz existuje a funguje - schovava sekciu predmeto-ucitela, ba aj stranku predmetu. Cele co treba je pridat do subjectHiding treti rezim ku existujucim dvom, taky ze stranka predmetu je vzdy viditelna. Ziaden kod netreba zakomentovavat, lebo sa to riadi stlpcom v Season. Vynimka pre ADMINa tiez uz existuje.

**Comment by Sameth** [comment]
Vyzera to tak, ze dokonca aj treti rezim bol spraveny, ale len implicitne. Pokusil som sa ho trosku zexplicitnit.
