### ISSUE TITLE
Skontrolovať stav arény / updatnuť VOTR a pod.

### ISSUE THREAD

**Issue by tvinar** [fmfi-svt/anketa#208]
Skontrolovať/rozbehať anketa arénu tak, aby fungovala a aby sa dal robiť pohodlný development.

**Comment by TomiBelan** [comment]
Arena ma zda sa viacere problemy:
* Pouziva vetvu master, ktora je uplne mimo. Treba fixy z unreviewed.
* V symfony cache je na zaciatku zly config. Mozno suvisi s prvym bodom.
* Defaultny obsah db je este zo stareho servera.

Kym pofixujem, tu je workaround:
```
anketaarena create menoareny unreviewed
cd /var/www/anketaarena/menoareny
./scripts/reset.sh
anketaarena import fmph aa_menoareny
```

Navyse je stary votr, ale to vid #202.

**Comment by tvinar** [comment]
workaround treba dopisat do dokumentacie

**Comment by mrshu** [comment]
Toto je uz vybavene, `anketaarena create menoareny` vyrobi dobru instanciu ankety, na ktorej sa uz moze pracovat.

Vdaka @TomiBelan za horny workaround, v zasade som to koncipoval podla toho.

**Comment by mrshu** [comment]
Este poznamenam, ze votr je tam stare este stary, ale to nejake priame problemy (aspon v mojom testovani) nesposobovalo.
