### ISSUE TITLE
Nedá sa nahlásiť chýbajúci učiteľ pri predmete

### ISSUE THREAD

**Issue by viktorsvetsky** [fmfi-svt/anketa#209]
V ankete pre FiF UK sa nedá nahlásiť chýbajúci učiteľ pri predmete. Hlási chybu.
![bug](https://cloud.githubusercontent.com/assets/16431139/11997749/1c255408-aa85-11e5-99cd-5bdd135b1f4e.png)

**Comment by tvinar** [comment]
Google SMTP sa tvarilo ze nebezpecny klient
Prestaveny google ucet aby bral aj nebezpecnych klientov
Odporucanie do buducna: pouzit nieco ine ako Google SMTP
