### ISSUE TITLE
Pozriet kratke kody predmetov (FMFI)

### ISSUE THREAD

**Issue by mrshu** [fmfi-svt/anketa#223]
FMFI pouziva skracovanie dlheho kodu predmetov na kratky. Kedze odstranovane casti kodov predmetov zacinaju mat zasadny vyznam, je treba pozriet, ci by nebolo lepsie sa na skracovanie vykaslat.

**Comment by tvinar** [comment]
Actually, stale uprednostnujeme "pekne" kody. Momentalne sa ale (pomerne vynimocne) naraz pouzivaju predmety s tym istym kodom, pricom sa lisia len verziou za poslednym lomitkom. Balast pred prvym lomitkou rozhodne nechceme.

**Comment by mrshu** [comment]
@tvinar bere to @vidriduch, moc sa mu to nepaci, ale zvladne.
