### ISSUE TITLE
tlacidlo "nieco nefunguje"

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#50]
Feature #53 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/53
Author: <strong>Martin Králik</strong>
Priority: Normal
Start date: 01/12/2012

<div class="wiki"> <p>Pridat na stranku niekam odkaz/tlacidlo/formular, kde moze clovek hned vyplnit aky ma problem a nam to posle mail.</p> </div>

<hr>

<em>Created by <strong>Martin Králik</strong> on 2012-01-12 at 10:25:15+01:00</em>

<ul><li><strong>Start date</strong> set to <i>01/12/2012</i></li><li><strong>Priority</strong> set to <i>Normal</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Subject</strong> set to <i>tlacidlo &quot;nieco nefunguje&quot;</i></li><li><strong>Tracker</strong> set to <i>Feature</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>Pridat na stranku niekam odkaz/tlacidlo/formular, kde moze clovek hned vyplni...</i> </li></ul>

**Comment by mrshu** [comment]
Toto nam asi treba, zrejme uplne stacit vyrobit poriadne `mailto:`, v ktorom budu prefillnute data, ktore sa nam budu pri debugovani hodit.
