### ISSUE TITLE
UI pre anonymizaciu

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#85]
Feature #85 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/85
Author: <strong>Martin Králik</strong>
Priority: Normal
Start date: 03/15/2012

<div class="wiki"> <p>nech nemusime rucne pustat query</p> </div>

<hr>

<em>Created by <strong>Martin Králik</strong> on 2012-03-15 at 17:22:15+01:00</em>

<ul><li><strong>Start date</strong> set to <i>03/15/2012</i></li><li><strong>Priority</strong> set to <i>Normal</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Subject</strong> set to <i>UI pre anonymizaciu</i></li><li><strong>Tracker</strong> set to <i>Feature</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>nech nemusime rucne pustat query</i> </li></ul>

**Comment by mrshu** [comment]
Neni uz treba, mame na taketo CLI tooling.
