### ISSUE TITLE
UI pre importy

### ISSUE THREAD

**Issue by svtimport** [fmfi-svt/anketa#86]
Feature #86 imported from https://svt-devel.fmph.uniba.sk/chiliproject/issues/86
Author: <strong>Martin Králik</strong>
Priority: Normal
Start date: 03/15/2012

<div class="wiki"> <p>idealne nieco velmi jednoduche: export z AISu -&gt; import do ankety<br/>pripade nieco pre jemne doladenie</p> </div>

<hr>

<em>Created by <strong>Martin Králik</strong> on 2012-03-15 at 17:23:31+01:00</em>

<ul><li><strong>Start date</strong> set to <i>03/15/2012</i></li><li><strong>Priority</strong> set to <i>Normal</i></li><li><strong>Project</strong> set to <i>Anketa</i></li><li><strong>Subject</strong> set to <i>UI pre importy</i></li><li><strong>Tracker</strong> set to <i>Feature</i></li><li><strong>Status</strong> set to <i>New</i></li><li><strong>Description</strong> set to <i>idealne nieco velmi jednoduche: export z AISu -&gt; import do ankety pripade ...</i> </li></ul>

**Comment by mrshu** [comment]
Robi sa cez VOTR, UI zrejme netreba.
